# Generated by Django 5.1.5 on 2025-01-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_is_vip_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
