# Generated by Django 4.2.17 on 2024-12-11 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0002_alter_quiz_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersquizzes',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.quiz'),
        ),
        migrations.AlterField(
            model_name='usersquizzes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
